# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Manual Upload Python Package to Test Env (Test PyPi)

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      test_version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Test deploy Version'
        # Default value if no value is explicitly provided
        default: '1.3.9.dev'
        # Input has to be provided for the workflow to run
        required: true
  
permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Clean Build
      run: |
        rm -rf psycopg2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools wheel twine
        python -m pip install psycopg2-binary -t . --upgrade
    - name: Alter Test Version
      run: |
        echo ${{ github.event.inputs.test_version }} > version.txt
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
    - name: Added Extras to Build package 
      run: |
        python compile_and_build.py
    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN_TEST }}
      run: |
        twine upload --repository testpypi dist/*
