# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Clean Directory
      run: |
        rm -rf psycopg2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements_test.txt ]; then pip install -U -r requirements_test.txt; fi
        python -m pip install --index-url https://test.pypi.org/simple/ aws-psycopg2 -U
    - name: List Directory
      run: |
        ls -l
    - name: Test with pytest
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        HOST: ${{ secrets.HOST }}
        DATABASE: ${{ secrets.DATABASE }}
        PORT: ${{ secrets.PORT }}
      run: |
        pytest
